[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Iplatform/foundation/include
    -Iplatform/core/include
    -Iplatform/hal/include

[env:native]
platform = native
build_flags =
    -Iplatform/foundation/include
    -Iplatform/core/include
    -Iplatform/hal/include
